### PR TITLE
Add rpm target

### PR DESCRIPTION
**Pull request by mehrdad-shokri**
Following [this](https://github.com/manojVivek/responsively-app/issues/318) issue I've successfully built and published app for rpm.  Please note that ``rpm-build`` package is required on the machine that runs ``npm run publish-linux``

Fixes: #318

### CODE REVIEW

**Comment by manojVivek** [comment]
@mehrdad-shokri Does this publish the package to the registry that can be installed using `yum`?

**Comment by mehrdad-shokri** [comment]
@manojVivek no it generates an ``rpm`` file inside ``release`` directory. I guess users have to download it from releases.  
It can be installed with ``rpm -U filename``

**Comment by mehrdad-shokri** [comment]
@manojVivek can we merge this?

**Comment by manojVivek** [comment]
@mehrdad-shokri Was waiting to verify the build from the build machine once. It is running fine, merging it. 🎉 
Looking forward to more collaboration like this in the future. 🙌

**Comment by manojVivek** [comment]
@all-contributors Please add @mehrdad-shokri for infra.

**Comment by manojVivek** [comment]
@mehrdad-shokri   Two things:

1. Can you let us know your Twitter handle? We would love to give a shout out for your work from our twitter account. 
2. Please join our community on Gitter - https://gitter.im/responsively-app/, for any discussions in the future.

**Comment by elektronik2k5** [comment]
I'd love to try it on Fedora. Should be installable via `sudo dnf install <path/to/filename.rpm>`.

**Comment by mehrdad-shokri** [comment]
@manojVivek sure my Twitter handle is @mehrdad_shokri.

**Comment by mehrdad-shokri** [comment]
@elektronik2k5 no rpm packages get installed via `sudo rpm -U <path_to_rpm_file>`

**Comment by elektronik2k5** [comment]
> @elektronik2k5 no rpm packages get installed via `sudo rpm -U <path_to_rpm_file>`

@mehrdad-shokri, please validate yourself before claiming someone's wrong. I said specifically Fedora, which uses `dnf`, which can install `.rpm` packages. Here are the docs: https://dnf.readthedocs.io/en/latest/command_ref.html#install-examples. Quoting for the lazy:

> `dnf install ~/Downloads/tito-0.6.2-1.fc22.noarch.rpm`
> Install a local rpm file tito-0.6.2-1.fc22.noarch.rpm from the ~/Downloads/ directory.

**Comment by mehrdad-shokri** [comment]
@elektronik2k5 thanks for mentioning

**Pull request merged**
