### PR TITLE
Develop shortcut managers without globalShortcut or localShortcut

### PR DESCRIPTION
**Pull request by jjavierdguezas**
Using mousetrap instead
Automatically register menu items with accelerators
Fix main window losing focus when hotkeys dialog closes
related to #90 
rewrote of #166

### CODE REVIEW

**Comment by jjavierdguezas** [comment]
@manojVivek I completely rewrote this idea without using `globalShortcut` or `localShortcut`.
I used [Mousetrap](https://craig.is/killing/mice) instead and the result is the same functionality but much simpler. I let you decide wich branch to merge, but I recommend this one, as far as I am concern we can drop the other one (#166)

**Comment by manojVivek** [comment]
@jjavierdguezas I'm with this PR. Have you tested that the existing shortcuts are working as it is and this change is not creating any issues shortcuts in other apps when Responsively is open right? 

Just wanted to confirm before merging it. 🙂

**Comment by jjavierdguezas** [comment]
> @jjavierdguezas I'm with this PR. Have you tested that the existing shortcuts are working as it is and this change is not creating any issues shortcuts in other apps when Responsively is open right?
> 
> Just wanted to confirm before merging it. 🙂

@manojVivek yes I tested it all and it does not mess with other apps. Registered shortcuts only work if the ResponsivelyApp main windows is focused. The shortcuts in the menu items still work just fine. In my last commit I fixed the accelerator for the `Open HTML file` menu item that did not work in Windows (it was defined as `Command+O` but `Command` does not work in Windows, I changed it to `CommandOrControl+O`). On the other hand, I think you should review the menu definition, because I saw that it looks different (it shows different menus and actions) when the operating system is darwing compared to windows and linux

**Comment by manojVivek** [comment]
@jjavierdguezas Thanks for taking care of the Open HTML bug too. 
Yeah, `menu.js` needs cleanup, it has different menu items for windows and Mac. But we keep it for later. :) 

I'm merging this PR now.

**Comment by jjavierdguezas** [comment]
> @jjavierdguezas Thanks for taking care of the Open HTML bug too.
> Yeah, `menu.js` needs cleanup, it has different menu items for windows and Mac. But we keep it for later. :)
> 
> I'm merging this PR now.

@manojVivek  great!, then I'll start working on registering some shortcuts like the ones in #90 , you can assign it to me

**Comment by manojVivek** [comment]
@jjavierdguezas I'm not able to assign it since you have not interacted directly with the card. Can you make a comment on it? 

Thanks!

**Comment by jjavierdguezas** [comment]
> @jjavierdguezas I'm not able to assign it since you have not interacted directly with the card. Can you make a comment on it?
> 
> Thanks!

done

**Pull request merged**
