### PR TITLE
Added shortcuts to help menu

### PR DESCRIPTION
**Pull request by romanakash**

### CODE REVIEW

**Comment by manojVivek** [comment]
@romanakash First of all thanks so much for the PR. Just a couple of thoughts:
1. Is it possible for you to convert this into a popup with HTML content? So that we can present the shortcuts in a more intuitive UI. 
2. If the above is not possible, Just formatting the text in the Popup would do too. In such a way that, the shortcuts section is aligned in line. 

Great work otherwise. 👍

**Comment by romanakash** [comment]
Pushed a new commit with a cleaner looking UI. The messageDialogBox api didn't allow for html content so I used a frameless BrowserWindow. The html content is loaded from app/shortcuts.html

**Comment by manojVivek** [comment]
@romanakash This looks excellent! Can you please add an `ok` button to have close the window?

**Comment by romanakash** [comment]
Oh yes completely forgot about that. Pushed a new commit

**Comment by manojVivek** [comment]
Great, merging this in. Thanks so much for the contribution @romanakash 🎉 
Looking forward to more of these. 

Also, would you mind sharing your twitter handle? We would just like to make a shout out there. 🙂

**Comment by manojVivek** [comment]
@all-contributors Please add @romanakash for code.

**Comment by romanakash** [comment]
Thank you. My Twitter is @romanakash27

**Pull request merged**
