### PR TITLE
Feature/open file with

### LINKED ISSUE #330: List `Responsively App` as an item in the native `Open With` applications list for html files

### PR DESCRIPTION
**Pull request by jjavierdguezas**
resolves #330 

@manojVivek I could only test it on windows

openwith

### CODE REVIEW

**Comment by manojVivek** [comment]
@jjavierdguezas Great, I'll check out this branch on Mac and check it out.

**Comment by manojVivek** [comment]
@jjavierdguezas Worked on Mac. 💯

@esprush Can you please check this one on Linux?

**Comment by jjavierdguezas** [comment]
hey @manojVivek @esprush I had access to an Ubuntu machine and first the `package-linux` command throws an error
>⨯ appimage.AppImageConfiguration.FileAssociations: []appimage.FileAssociation: appimage.FileAssociation.Ext: ReadString: expects " or n, but found [...

I think is related to [this electron-builder issue](https://github.com/electron-userland/electron-builder/issues/3204)

I spli the `ext` array in two whole entries and the build finished successfully but I couldn't see `ResponsivelyApp` listed in the `Open With` menu 😞 . I tried with different options from [the documentation](https://www.electron.build/configuration/configuration#PlatformSpecificBuildOptions-fileAssociations) but I couldn't open an `html` file from the OS menu

**Comment by jjavierdguezas** [comment]
I think maybe this is not supported for `AppImage` builds?
see 
image

on https://www.electron.build/configuration/appimage

**Comment by manojVivek** [comment]
>I think maybe this is not supported for `AppImage` builds?
> see

So installing it using `AppImageLauncher` enables desktop integration?

**Comment by jjavierdguezas** [comment]
>So installing it using AppImageLauncher enables desktop integration?

I'm out of my league here 😅 but it seems so, I really don't know

**Comment by manojVivek** [comment]
> I'm out of my league here 😅 but it seems so, I really don't know

Yeah ok. 🙂 
Let's wait and hear from @esprush.

**Comment by esprush** [comment]
@jjavierdguezas @manojVivek it did not work when I tried with AppImageLauncher also.
even the protocol register that integrates with chrome extension also is not registered.

options to make this work:
1) create .desktop file with the supported file associations
2) add it to /usr/share/applications/mimeapps.list

this is also more like a workaround and no luck for an electron build based solution as far I checked :(

reference - https://askubuntu.com/questions/819782/how-do-i-associate-a-file-type-with-an-appimage

**Comment by jjavierdguezas** [comment]
@esprush about chrome protocol, did this PR break that?

**Comment by manojVivek** [comment]
Ok, in that case, let's push this live so that it will work for Windows and Mac until we figure out the solution for Linux. 

@jjavierdguezas Is that alright?

**Comment by manojVivek** [comment]
> @esprush about chrome protocol, did this PR break that?

I think he is talking about the protocol handler for opening the `responsively://` URLs in the app.

**Comment by jjavierdguezas** [comment]
> > @esprush about chrome protocol, did this PR break that?
> 
> I think he is talking about the protocol handler for opening the `responsively://` URLs in the app. 

yes about that, does this PR break that?

**Comment by esprush** [comment]
@manojVivek I dont think the chrome protocol was working previously also.

**Comment by esprush** [comment]
I will check the possibility of doing this through the electron shell.

**Pull request merged**
