### PR TITLE
Basic status bar

### LINKED ISSUE #153: Add a status bar with key info and useful links.

### PR DESCRIPTION
**Pull request by manojVivek**
Fixes #153 
Screenshot: 
Screenshot 2020-06-17 at 1 49 41 PM

### CODE REVIEW

**Comment by Grafikart** [comment]
Could we have an option to hide this status bar (if we are short on screen height ?)

**Comment by jjavierdguezas** [comment]
Hey @manojVivek do you know you can subscribe to the `'status-changed'` event of the `AppUpdater` (like [here](https://github.com/manojVivek/responsively-app/blob/ff41bf779989ea01625c3c1bbab41f3b2d8734a8/desktop-app/app/main.dev.js#L298)) and show its status transitions in this status bar?

**Comment by manojVivek** [comment]
> Could we have an option to hide this status bar (if we are short on screen height ?)

@Grafikart Will add it with #198

**Comment by manojVivek** [comment]
> Hey @manojVivek do you know you can subscribe to the `'status-changed'` event of the `AppUpdater` (like [here](https://github.com/manojVivek/responsively-app/blob/ff41bf779989ea01625c3c1bbab41f3b2d8734a8/desktop-app/app/main.dev.js#L298)) and show its status transitions in this status bar?

@jjavierdguezas We can address it with #199 as discussed.

**Pull request merged**
