### PR TITLE
updated address bar so that the floating icons and url does not overlap

### PR DESCRIPTION
**Pull request by AARYAN-MAHENDRA**
just changed the styles file.

### CODE REVIEW

**Comment by manojVivek** [comment]
@AARYAN-MAHENDRA Thank you so much for the work on this. Merging this now. 🎉

**Comment by manojVivek** [comment]
@all-contributors Please add @AARYAN-MAHENDRA for code.

**Comment by manojVivek** [comment]
@AARYAN-MAHENDRA  Would you mind sharing your twitter handle? We would love to send a shout out on twitter for this work! 🙂

**Comment by AARYAN-MAHENDRA** [comment]
[https://twitter.com/i/connect_people?user_id=1270600876369969153](url) @MahendraAaryan

And Thankyou for appreciating my work😊😊

**Pull request merged**
