### PR TITLE
Fix animation when opening the Drawer

### PR DESCRIPTION
**Pull request by vlazaroes**
Previously, width was used in animation, this caused strange animation when opening the Drawer.

This solution uses the property of margin and achieves smoother animation.

### CODE REVIEW

**Comment by manojVivek** [comment]
@vlazaroes This is wonderful, can you please resolve the merge conflicts?

**Comment by vlazaroes** [comment]
@manojVivek Solved.

**Comment by manojVivek** [comment]
@vlazaroes Great, thanks for making it better. Merging this in now, looking forward to more collaboration like this! 🙌

**Comment by manojVivek** [comment]
@all-contributors Please add @vlazaroes for code.

**Comment by manojVivek** [comment]
@vlazaroes Two things:

1. Can you let us know your Twitter handler? We would love to give a should out for your work from our twitter handle. 
2. Please join our community on Gitter - https://gitter.im/responsively-app/, for any discussions in the future.

**Pull request merged**
