### PR TITLE
Scrollbar update to match app's user interface

### PR DESCRIPTION
**Pull request by Kidcredo**
As the issue #194 that I reported a while ago. This make the scrollbar appear consistent with the UI of the app.

Before 
image
After
image

### CODE REVIEW

**Comment by manojVivek** [comment]
@Kidcredo This is great work! I really appreciate you sending a fix for the issue you reported! 
Merging this in!

**Comment by manojVivek** [comment]
@all-contributors Please add @Kidcredo for code and test.

**Comment by manojVivek** [comment]
@Kidcredo Do you might sharing your Twitter handle? We would love to send a shout out for your work on twitter. :)

**Comment by Kidcredo** [comment]
My twitter handle is @Kidcredo and also this is my first open source contribution.

**Pull request merged**
