### PR TITLE
docs: fix typos and inconsistencies in home page

### PR DESCRIPTION
**Pull request by jaunesarmiento**
Heya! I just found a few typos and fixed them for you. Cheers!

### CODE REVIEW

**Comment by manojVivek** [comment]
@jaunesarmiento Jaune, thanks for fixing these terrible errors. 😅 
Merging this in, looking forward to more like this in the future. 🙌

**Comment by manojVivek** [comment]
@all-contributors Please add @jaunesarmiento for content.

**Comment by manojVivek** [comment]
@jaunesarmiento  Two things:

1. Can you let us know your Twitter handler? We would love to give a shout out for your work from our twitter handle. 
2. Please join our community on Gitter - https://gitter.im/responsively-app/, for any discussions in the future.

**Comment by jaunesarmiento** [comment]
I can join gitter but I don’t have Twitter 😂. It’s all good though no need to mention me.

**Pull request merged**
