### PR TITLE
Added scroll behavior css

### PR DESCRIPTION
**Pull request by kishoreio**
Added scroll behavior CSS for smooth transitions when user clicks the header nav links.

### CODE REVIEW

**Comment by manojVivek** [comment]
This is great, thanks @kishoreio

**Comment by kishoreio** [comment]
👍

**Comment by manojVivek** [comment]
@all-contributors Please add @kishoreio for code

**Comment by kishoreio** [comment]
Can you add my github profile link instead of my personal website?
Here's my Github link - https://github.com/kishoreio

**Pull request merged**
